Check for env vars

diff --git a/getSynchronizer b/getSynchronizer
--- a/getSynchronizer
+++ b/getSynchronizer
@@ -1,8 +1,11 @@
 #!/bin/sh
 
-curl --basic -u ${DLOGIN}:${DPASS} \
-   "http://${DHOST}/odata/v1/Synchronizers($1)" 2>/dev/null \
-   | xmllint --format -
+if [ -z "${DHOST+x}" -o -z "${DLOGIN+x}" -o -z "${DPASS+x}" ]; then
+  echo 'Error: environment variables are not set'
+  exit 1
+fi
 
-echo ""
+curl -sS --basic -u ${DLOGIN}:${DPASS} \
+   "http://${DHOST}/odata/v1/Synchronizers($1)" \
+   | xmllint --format -
 
diff --git a/stopSync b/stopSync
--- a/stopSync
+++ b/stopSync
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ -z "${DHOST+x}" -o -z "${DLOGIN+x}" -o -z "${DPASS+x}" ]; then
+  echo 'Error: environment variables are not set'
+  exit 1
+fi
+
 ID=$1
 
 m4 -D_ID=$ID -D_REQUEST=stop body.txt > body.tmp
